# Generated by Django 2.2.8 on 2019-12-11 14:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('sigla', models.CharField(max_length=10)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('color', models.CharField(max_length=7)),
                ('foto_usuario', models.ImageField(default='usuario/default.png', upload_to='usuario/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('texto_nota', models.TextField()),
                ('imagen', models.ImageField(default='notas/default.png', upload_to='notas/%Y/%m/%d')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PDTE', 'Pendiente'), ('TERM', 'Terminada'), ('ANUL', 'Anulada')], max_length=20)),
                ('importancia', models.CharField(choices=[('MAX', 'Prioridad Máxima'), ('ALT', 'Prioridad Alta'), ('MED', 'Prioridad Media'), ('BAJ', 'Prioridad Baja')], max_length=20)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.Categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.Usuario')),
            ],
        ),
    ]
